### ISSUE TITLE
Add support for flexi variants in the cart/checkout

### ISSUE THREAD

**Issue by simonwalsh** [sprangular/sprangular#101]
We want to be able to use the flexi-variants gem (https://github.com/jsqu99/spree_flexi_variants).

Basically, we just need to create a third param to the `Cart.addVariant` service method (and the services ).

**Comment by simonwalsh** [comment]
options: 
  [
    {
      id: 12345
      value: "Foo"      
    },
    {
      id: 67890
      value: ""      
    }
  ]

**Comment by simonwalsh** [comment]
This impacts:
- [ ] cart service
- [ ] add-to-cart directive
- [ ] cart controller

**Comment by simonwalsh** [comment]
We need to receive two things from the server:
1. the ad-hoc types, with its children (possible values)
2. the customization types

For those, we need the ID, slug and presentation.

**Comment by joshnuss** [comment]
@simonwalsh what do you think about doing this as an extension? Cause not all sites need this feature

**Comment by simonwalsh** [comment]
@joshnuss I kind of backtracked a little in my integration of the whole thing, but I would love to have a way of being able to reuse what is already in Sprangular, but just adding extra params to the API calls... 

I thought using an optional param was a good middle ground solution but I'm up for suggestions. This won't be used for a little while anyway in production, so plenty of time to refactor!

**Comment by bryanmtl** [comment]
Let's move this to an extension, certainly not a core feature for me.
