### ISSUE TITLE
Refactor relevant API to allow cache

### ISSUE THREAD

**Issue by simonwalsh** [sprangular/sprangular#108]
Add a `cache:true` param to API calls that can/should be cached. Angular will create a copy of the data in memory and use this data as the response instead of allowing the API call.

e.g. https://github.com/sprangular/sprangular/blob/master/app/assets/javascripts/sprangular/services/catalog.coffee#L13-L16

**Comment by simonwalsh** [comment]
The only real challenge here is the `in_stock` status of the product. 
- Could there be a separate call for this when we get to the product page ?
- Should we not have the PDP cached at all ?
- How does this impact the add-to-cart from the index page ?

One simple solution would be to only deal with the out of stock status once the user has clicked on the button and the call as been made to the server, albeit this is not very user friendly. Still, we are talking about the edge case here where the stock would be depleted in between the moment the user gets to the site and the moment he wants to add to cart.

Thoughts @joshnuss @bryanmtl?

**Comment by simonwalsh** [comment]
We are currently working on making the server responses wayyyyy faster so this might be futile for the fure.

**Comment by joshnuss** [comment]
@simmer Think Bry has some codez to cache inventory data (we definitely need to get rid the repeated queries to find on_hand. See #100
