### ISSUE TITLE
Add string mapping service to allow custom error messages

### ISSUE THREAD

**Issue by bourroush** [sprangular/sprangular#109]
We need to be able to change the form validation error message. Either just to customize it, but even for multilingual websites.

**Comment by joshnuss** [comment]
cool, will update the validity.js tomorrow

On Mon, Mar 16, 2015 at 2:17 PM, bourroush <notifications@github.com> wrote:

> Assigned #109 <https://github.com/sprangular/sprangular/issues/109> to
> @joshnuss <https://github.com/joshnuss>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sprangular/sprangular/issues/109#event-255891813>.
>



-- 
Joshua Nussbaum

**Comment by bourroush** [comment]
Hi @joshnuss, any update on this one.. ? Thanks ! :)

**Comment by joshnuss** [comment]
@bourroush all fixed now. Example is here: https://github.com/sprangular/sprangular/blob/master/config/locales/en.yml#L144
