### ISSUE TITLE
Checkout - "Shipping is not available to ." on landing

### ISSUE THREAD

**Issue by LaurentDario** [sprangular/sprangular#110]
When landing on the checkout page after login, with an address already registered, the site always tells me that the shipping is not available.

![screen shot 2015-03-16 at 2 56 45 pm](https://cloud.githubusercontent.com/assets/234418/6674007/53eb0b5c-cbed-11e4-8771-5f70e138e4d9.png)

**Comment by rposborne** [comment]
Yea we are seeing this too.   It also affects the tax calculations.

**Comment by joshnuss** [comment]
Updates coming to checkout in this branch: https://github.com/sprangular/sprangular/tree/feature/one-page-checkout will make sure that issue is fixed.

**Comment by joshnuss** [comment]
Fixed by ad2b1c172755fbbf7461a4db26ffd196db053933
