### ISSUE TITLE
An address with an invalid zipcode prevents the order from completing a checkout

### ISSUE THREAD

**Issue by bryanmtl** [sprangular/sprangular#126]
For stores that require a [zip code](https://github.com/spree/spree/blob/master/core/app/models/spree/address.rb#L14), checkout will not continue if an incorrect zipcode is entered. 

Spree validates the zipcode in this method:
```
def postal_code_validate
  return if country.blank? || country.iso.blank? || !require_zipcode?
  return if !TwitterCldr::Shared::PostalCodes.territories.include?(country.iso.downcase.to_sym)

  postal_code = TwitterCldr::Shared::PostalCodes.for_territory(country.iso)
  errors.add(:zipcode, :invalid) if !postal_code.valid?(zipcode.to_s)
end
```

The problem is two-fold. First, we shouldn't be trying to persist the address until the full address has been  entered, not with each keypress. Perhaps a "continue" button is needed here. 

The second problem is that this failure isn't bubbled up to the UI, the user isn't aware that there's an error and refreshing is the only way to continue. 

cc: @LaurentDario

**Comment by joshnuss** [comment]
Fixed by checkout refactoring.
