### ISSUE TITLE
Address validation with EasyPost

### ISSUE THREAD

**Issue by bryanmtl** [sprangular/sprangular#127]
https://www.easypost.com/address-verification-api

This is an interesting service. I'd like to evaluate using this to validate addresses properly before asking for shipping rates.

**Comment by joshnuss** [comment]
PR is here: https://github.com/DynamoMTL/spree_easypost/pull/2

**Comment by bryanmtl** [comment]
@joshnuss - Looks great, thank you. I'll test this out later today.

**Comment by joshnuss** [comment]
Think we can close this now
