### ISSUE TITLE
Address order on checkout process

### ISSUE THREAD

**Issue by rodrigodalcindev** [sprangular/sprangular#129]
Ideally, users should be prompted to fill out their shipping address first, then opt to have their billing information based on the shipping address. I understand that making this change on a project-by-project basis requires a lot of effort, so maybe it would be a better idea to have this be the default flow.

![screen shot 2015-04-01 at 9 47 28 am](https://cloud.githubusercontent.com/assets/865198/6942581/8a392a02-d856-11e4-9d4e-258de27b2bb6.png)
(Reference: https://staging.glossier.com/#!/checkout)

**Comment by bryanmtl** [comment]
@rodrigodalcindev Good call @rodrigodalcindev, I'm :+1: for this change.

**Comment by joshnuss** [comment]
Closed by 9288d07879f177deb503369701e1e9783dbb788d
