### ISSUE TITLE
Refactor checkout code and flow

### ISSUE THREAD

**Issue by bryanmtl** [sprangular/sprangular#130]
@joshnuss Opening up an issue here for this. As discussed on Slack, let's replace the current checkout flow with our version from Glossier. 

Doing so will resolve #129 and #91 and we'll be able to take advantage of code that's been properly battle tested. 

cc: @simonwalsh @frahugo

**Comment by simonwalsh** [comment]
@joshnuss Please feel free to refactor anything, especially the duplication of billing and shipping code... This has been done amidst the rush of launch and is a bit... weird.

**Comment by bryanmtl** [comment]
@simonwalsh I would hold off on refactoring for now. I want to focus on getting the tested version in and then refactoring from there. With the backlog of sites we need to launch, I want to prioritize stability.

**Comment by joshnuss** [comment]
Done
