### ISSUE TITLE
Refactor to use a minification-friendly syntax

### ISSUE THREAD

**Issue by simonwalsh** [sprangular/sprangular#160]
To be able to use minification/uglification, we need to insure that we map the injected modules to the functions parameters like so:

```
Sprangular.service "Cart", [ '$http', ($http) ->
  ...
]
```

instead of this:

```
Sprangular.service "Cart", ($http) ->
  ...
```

**Comment by joshnuss** [comment]
@simonwalsh Already doing that! We are currently using the [ng-annotate](https://github.com/olov/ng-annotate) rails gem, which automatically rewrites the code as in your example.
