### ISSUE TITLE
IgnoreLoadingIndicator isn't working when fetching products

### ISSUE THREAD

**Issue by bryanmtl** [sprangular/sprangular#162]

**Comment by joshnuss** [comment]
It should work now on master, wanna give it a try? https://github.com/sprangular/sprangular/blob/master/app/assets/javascripts/sprangular/services/catalog.coffee#L55

**Comment by bryanmtl** [comment]
@joshnuss Does #163 need to be merged or does your change make it redundant?

**Comment by joshnuss** [comment]
@bryanmtl this one shouldnt be needed anymore
