### ISSUE TITLE
Asset was linked to from an alias rather than its exact path (Sprockets::Rails::Helper::AssetAliasUsed)

### ISSUE THREAD

**Issue by fuzzytern** [sprangular/sprangular#164]
Cloning sprangular-demo, then executing the server (after db:reset spree_sample:load), leads to this error:

    Sprockets::Rails::Helper::AssetAliasUsed in Sprangular::Home#index
    Showing /[...]/sprangular-a77bca44e9e2/app/views/sprangular/shared/_templates.html.slim where line #1 raised:
    Asset was linked to from an alias rather than its exact path. Alias resolving may not be available in production.
    Use "layout/navbar_links.html" instead of "layout/navbar_links.html.slim"

It seems related to a Sprockets issue ([here](https://github.com/rails/sprockets-rails/issues/246) and [here](https://github.com/rails/sprockets/issues/42)) though it's happening with slim templates and not jpg files.

**Comment by braidn** [comment]
@fuzzytern if you back sprocket-rails off to `~> 2.2.0` you should be golden for now. No need to bump to the GitHub version or a beta of sprocket-rails.

**Comment by fuzzytern** [comment]
Absolutely @braidn! Thanks for you wise insights.
