### ISSUE TITLE
Could not find gem rails-assets-angular-animate

### ISSUE THREAD

**Issue by ccfiel** [sprangular/sprangular#186]
I have done a fresh install but I got this error doing a bundle install
 
Bundler could not find compatible versions for gem "rails-assets-angular-animate":
  In Gemfile:
    sprangular (= 0.1.0) ruby depends on
      rails-assets-angular-animate (>= 0) ruby
Could not find gem 'rails-assets-angular-animate (>= 0) ruby', which is required by gem 'sprangular (= 0.1.0) ruby', in any of the sources

Any idea what is causing the problem?

**Comment by joshnuss** [comment]
Hi @ccfiel!

Did you define `source "https://rails-assets.org"` in your `Gemfile`?

**Comment by ccfiel** [comment]
Hello @joshnuss 

Yes it has but its weird I tried to reinstall today. I got another error. I will just create a new issue and close this one.
