### ISSUE TITLE
Bundler could not find compatible versions for gem "rails"

### ISSUE THREAD

**Issue by poulping** [sprangular/sprangular#189]
Hello,
I am new to Rails and Ruby in general, so I am probably doing something wrong.
I tried installing sprangular using the recommended method of `sprangular install <app_name>`

After install, I get the following notice:
`The git source git://github.com/spree/spree_gateway.git is not yet checked out. Please run `bundle install` before trying to start your application`

when doing `bundle install` i get the following warning:

 `Warning: this Gemfile contains multiple primary sources. Using `source` more than once without a block is a security risk, and may result in installing unexpected gems. To resolve this warning, use a block to indicate which gems should come from the secondary source. To upgrade this warning to an error, run `bundle config disable_multisource true`.`

It starts to install and then 

```
Resolving dependencies......
Bundler could not find compatible versions for gem "rails":
  In Gemfile:
    spree_core (= 2.4) ruby depends on
      rails (~> 4.1.8) ruby

    rails (= 4.2.3) ruby
```

From what i understand, the problem comes from  the fact that the Gemfile indicates this `# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
 gem 'rails', '4.2.3'` but spree requires another version ?

ruby version: ruby 2.2.1p85
rails version: 4.2.3

Thanks !

**Comment by schickm** [comment]
You're gem file probably has the rails version specified explicitly

    gem 'rails', '4.2.3'

Just remove the explicit version and then bundler will install the rails version required by spree

    gem 'rails'
