### ISSUE TITLE
Multi-Currency 

### ISSUE THREAD

**Issue by iamkevingreen** [sprangular/sprangular#36]
I see this snippet in the add_to_cart_button which claims to be grabbing the currency but doesn't seem to do anything:

`| {{(variant || product).price * quantity  | number: 0 | currency}}`

I have set the default currency in the backend to EUR and changed the default currency on the product itself to be EUR but still displaying the USD currency on the front-end. This issue occurs throughout the front-end to anywhere pricing occurs. 

Not sure if I am doing something wrong, or if the functionality isn't totally there for currency switching yet?

**Comment by rposborne** [comment]
This is being tracked in #87

**Comment by joshnuss** [comment]
Thanks, closing this.
