### ISSUE TITLE
Remove unnecessary calls to update an order during checkout

### ISSUE THREAD

**Issue by bryanmtl** [sprangular/sprangular#57]
Specifically: https://github.com/DynamoMTL/sprangular/blob/master/app/controllers/spree/api/checkouts_controller_decorator.rb#L20-L22

Reverting the order back to the cart state during the quick update is problematic. We should avoid doing this, unless absolutely necessary.

**Comment by joshnuss** [comment]
Its also duplicating address and credit card info.

Will extract logic to class and refactor it.

**Comment by bryanmtl** [comment]
Awesome.

**Comment by joshnuss** [comment]
- [ ] when reverting to `cart` state, check if already in `cart` state, if in `cart` state skip
- [ ] when adding an item to cart, dont try moving to `payment` state
- [ ] when addresses change, move back to `address` state, update order and then move to `delivery` state
- [ ] when shipping rate changes, ensure in `delivery` state, set `shipping_rate_id` and move to `payment`
- [ ] add parameter `payment=true` to url, for when user hits "continue" button in checkout screen

**Comment by joshnuss** [comment]
Fixed
