### ISSUE TITLE
calling empty followed by addVariant does not add the new variant to the cart but instead increments the quantity

### ISSUE THREAD

**Issue by mickeyren** [sprangular/sprangular#69]
a call to Cart.empty() followed by a call to addVariant on an existing variant in the cart will result in incrementing the existing quantity on the existing variant in the cart already despite calling Cart.empty()

```
    empty: ->
      $http.delete '/api/cart'
        .success(@load)

    addVariant: (variant, quantity) ->
      foundProducts = @findVariant(variant.id)

      if foundProducts.length > 0
        @changeItemQuantity(foundProducts[0], quantity)
      else
        params = $.param(variant_id: variant.id, quantity: quantity)

        $http.post '/api/cart/add_variant', params, ignoreLoadingIndicator: true
          .success (response) ->
            service.load(response)
```

Wondering if this is really the intentional behaviour? I was expecting a call to empty would completely clear the cart.

**Comment by joshnuss** [comment]
@mickeyren Have you tried doing this using promises?

Something like:

```coffeescript
Cart.empty().then ->
   Cart.addVariant(variant, 1)
```

**Comment by joshnuss** [comment]
@mickeyren were you able to try that solution? LMK if it works

**Comment by joshnuss** [comment]
Hey @mickeyren 

Confirmed working on master, so closing this one. (re-open if you still find this is an issue)
