### ISSUE TITLE
New GET request each time a product index is visited

### ISSUE THREAD

**Issue by simonwalsh** [sprangular/sprangular#75]
To reproduce:

- go to the product listing page
- see that there is a GET request being done to the API
- go somewhere else
- either click the back button or navigate back to the same product page

The result:

- a new GET is being made everytime to fetch the same products

Maybe solutions:

- store those products in an attribute of the `Catalog` service and check this first ?
- apply caching on this request ?
- use local storage ?

**Comment by joshnuss** [comment]
@simonwalsh  if we cache the product data, what happens if item goes out of stock?

**Comment by simonwalsh** [comment]
@joshnuss On Glossier, we have this logic in the `add-to-cart` failsafe where you can add to cart but in the response of the PUT or POST, you have an error message saying the item is OOS... 

Then we refresh the UI of that item.

Could be annoying for the user I agree but those are edge cases vs the super long page refresh...

Thoughts?

**Comment by joshnuss** [comment]
Like the idea of warning when unable to add to cart.

What do you think of this: http://jmdobry.github.io/angular-cache/ for caching locally with expiration?
The key would be the requested params: (search, taxon etc), and then we can have another cache where the key is product permalink.

This way both the PDP and listing pages look at the local cache first.

**Comment by simonwalsh** [comment]
That sounds like a plan! I will put this in my pipeline (unless it is very urgent).

**Comment by joshnuss** [comment]
Thanks @simonwalsh!

**Comment by simonwalsh** [comment]
To-dos:
- [ ] integrate and test `angular-cache`
- [ ] add a failsafe to the add-to-cart flow
  - [ ] server returns an error with OOS warning
  - [ ] we warn the user (how?)
  - [ ] update the template (how?)

**Comment by joshnuss** [comment]
We can update the user, by setting `Variant.in_stock = false`

As for warning the user, I think it relates to #59, once we implement a tooltip/popover, we can handle the situation when item failed to be added to the cart in the same ux

**Comment by simonwalsh** [comment]
:+1:
