### ISSUE TITLE
Create a Filter service and logic

### ISSUE THREAD

**Issue by simonwalsh** [sprangular/sprangular#82]

**Comment by simonwalsh** [comment]
Been working on a filtering features on H&C here : https://github.com/DynamoMTL/hughandcrye.com/issues/386

The idea is to be able to filter products based on their variant (size) but also on their options (like 'color', 'pattern', etc.).

**Comment by joshnuss** [comment]
`ProductList` controller now supports dynamical filtering (via query string or via `$scope.filters`)
