### ISSUE TITLE
i18n support on frontend

### ISSUE THREAD

**Issue by rposborne** [sprangular/sprangular#84]
We have a need for translation support for sprangular.   Currently we have mashup between i18n-next via [ng-i18n](https://github.com/i18next/ng-i18next).   Would you all entertain features along this line being brought into master?   I don't think it would be reasonable as a plugin as it would require 100% alteration of template files.   Thoughts?

**Comment by joshnuss** [comment]
Yes, we'd like to support i18n

Currently we're integrating sprangular into english only sites, so it hasnt come up yet, but it would be a great feature to have. PR is welcome.

(Same goes for multi-currency support)

**Comment by rposborne** [comment]
So currently we have one functional concept, using the above angular / js solution.  Another possible solution is use Rails i18n features and have templates complied with each supported locale which prevent an additional http request, but goes against the "grain". 

The current solution sets locale based upon browser information, and does an async post request back to the server to set session locale for spree-i18n support.  This most likely is unavoidable.

**Comment by joshnuss** [comment]
I think the rails based approach could work, basically translate everything in `config/locales/<lang>.yml` files. And then render the translation table the first time the page is requested.

```coffeescript
angular.module('Sprangular').constant 'Translations',
   locale: 'fr'
   mappings:
     "bla bla": "la la la"
```

And then if the user switches locales, we just request the new translation table from the server. And save the choice in a cookie or `localStorage`.

**Comment by rposborne** [comment]
Yup this is basically what we have in i18n-next feature set.  We store the translations in the rails en.yml ... etc.  And upon locale swap, hit a custom end point that reads the translations and delivers it to the client. + caching of course.

**Comment by rposborne** [comment]
I'll get to cleaning it up and put up a pull request so it's a bit clearer.

**Comment by joshnuss** [comment]
Awesome

Also, it should support loading translations from extensions too.

we can handle that by by standardizing on a key in the `locales/locale.yml` file:

```ruby
# in config/locales/en.yml
en:
  sprangular:
     ....translations related to frontend go here...
```

and then in the extensions, we use the same key.

This way when we render out the translations we can pull them from the host site, extensions and core (in that order).

**Comment by rposborne** [comment]
See #87
