### ISSUE TITLE
Store global data objects in service attributes to avoid fetching multiple times and share between controllers and other services

### ISSUE THREAD

**Issue by simonwalsh** [sprangular/sprangular#85]
Noticed something that could be improved: when fetching data that is general to the whole site in a service api call, let's store it into an attribute of that service so... 
- that it is easily accessible in another service or a controller 
- that we don't have to do another api call to re-request the same data
- that we don't have to depend on a parent controller for that data

A good example of that could be https://github.com/sprangular/sprangular/blob/master/app/assets/javascripts/sprangular/services/catalog.coffee#L13-L16

I will open up a PR and try to come up with a good pattern that we can then apply to other services.

**Comment by joshnuss** [comment]
Yo @simonwalsh, maybe we can accomplish this by adding a `cache: true` to the `$http.get`

**Comment by simonwalsh** [comment]
Sure! Good idea. I would also provide a way to bust that cache tho. I will think about something. I did some test with this flow and it seems like it could work : 

https://github.com/sprangular/sprangular/blob/feature/85-services-shareable-data/app/assets/javascripts/sprangular/services/catalog.coffee#L16-L26

Tell what you think!

**Comment by joshnuss** [comment]
Cool

Do we have a use case for busting the cache? (I can see it being useful, just wanna make sure we will use it)

This could be also be doable as an interceptor. Like `$http.get(url, cache: true, refetch: true)`.

I'd prefer not to have $q promises created in a business service. Lots of nesting. Either interceptor or helper function/service would be the ideal place for it.

OR

We can use that angular-cache package.  (not sure if it supports manual cache-busting)

**Comment by simonwalsh** [comment]
Maybe we don't need that busting for things like taxonomies... 

But I would still see this kind of flow be used for products for instance, which I think we could want them to be refreshed (with vigor!). Unless we use another strategy for that.

As for using interceptors/helpers, we should sit down together as I'm not sure how this is done. Or maybe you show me an example.

**Comment by DanielWright** [comment]
My relatively uninformed $0.02: caching (and cache-invalidation) are such tricky problems that it's usually best to implement it as a reaction to pain (ie. when there's a measurable performance impact due to cacheable requests). Are you seeing performance drag on taxonomy API requests?

**Comment by simonwalsh** [comment]
I totally understand your point. Had issues in the past with caching.

The point is though to make an easily available _copy_ of the fetched data that will be accessible to the other entities feeding on it. Services in angular were built as a means to easily share data between controllers and services.

For example, if I create a service that does a GET to the API, but doesn't store the result internally (in an attribute of itself), it means I need to either ...
- refetch the same data in all the controllers that needs it (out of the question),
- store that data globally in a controller (not very elegant, out of the question).

By storing that fetched data in the service, it will nicely be available to all the controllers that needs that data.

So to come back to your point, there are no issues with the API call itself (slowness, etc.) but there is a structural issue with us needing to call it multiple times, hence the _caching_ (which in my mind should be more like _temporarly storing_).

**Comment by DanielWright** [comment]
Ahh, I understand better. What you're describing is more like memoization, which is a lot less of a hairy beast, since it's relatively short-lived and deterministic, so it doesn't beget a lot of the cache-invalidation issues.

**Comment by simonwalsh** [comment]
Exactamente!
