### ISSUE TITLE
Checkout address form submits on change

### ISSUE THREAD

**Issue by simonwalsh** [sprangular/sprangular#89]
When filling the address form in the checkout, the form submits when these conditions are met:
- When changing the value of the last non-filled input in the form
- When the rest of the form is filled
- When the inputs are valid

This means that the moment you put one character in a text field, for example, the form is submitted.

This behaviour should be changed to be fired on blur of the fields at least or, better yet, leave the choice to the user.

**Comment by simonwalsh** [comment]
As an additional issue or question, I'm not sure this line does proper validation:

```
validateAddress = (address) ->
  $scope.isValid = address.firstname && address.lastname && address.city && address.address1 && address.zipcode && address.country && address.state && address.phone
```

https://github.com/sprangular/sprangular/blob/master/app/assets/javascripts/sprangular/directives/shippingRatesSelection.coffee#L27-L28

**Comment by LaurentDario** [comment]
To add to this issue, I get a weird bug telling me to correct the errors below but with no error in the form
![screen shot 2015-03-16 at 2 58 10 pm](https://cloud.githubusercontent.com/assets/234418/6673965/11ca2abe-cbed-11e4-99a6-2aabb44e9fcf.png)

**Comment by joshnuss** [comment]
Thanks guys, will look at this guy tomorrow.

May rework the validation a bit to use something more angular friendly.

On Mon, Mar 16, 2015 at 2:59 PM, Laurent Dario <notifications@github.com>
wrote:

> To add to this issue, I get a weird bug telling me to correct the errors
> below but with no error in the form
> [image: screen shot 2015-03-16 at 2 58 10 pm]
> <https://cloud.githubusercontent.com/assets/234418/6673965/11ca2abe-cbed-11e4-99a6-2aabb44e9fcf.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sprangular/sprangular/issues/89#issuecomment-81872776>
> .
>



-- 
Joshua Nussbaum

**Comment by joshnuss** [comment]
Fixed by checkout refactoring
