### ISSUE TITLE
Checkout Addresses are bound to Billing and Shipping

### ISSUE THREAD

**Issue by LaurentDario** [sprangular/sprangular#90]
Would it be a way to use more than 2 addresses.
Right now, the two addresses registered under one user are the billing and the shipping address.
Is there an easy way to make it a list of multiple addresses that could be billing and/or shipping so that I can pick any of these addresses in both sections in the checkout ?

**Comment by joshnuss** [comment]
We might need to add support for spree_address_book to accomplish that

**Comment by bryanmtl** [comment]
Spree address book isn't my favourite extension. I believe that, since 2.4, multiple addresses are now properly associated with the user. If this isn't the case, we can make this a core feature of Sprangular and/or commit it back to Spree.

**Comment by joshnuss** [comment]
OK cool, looks like when we initially implemented, the User model didnt have addresses, not that 2.4 supports it, I will update the API response and JS deserialization code.

**Comment by joshnuss** [comment]
Hey guys, looked into it and current spree version, only saves the last ship/bill address id in the user table. Its a belongs to relationship, see https://github.com/spree/spree/blob/2-4-stable/core/app/models/concerns/spree/user_address.rb#L6

Not sure if we should query all complete orders, and pull address details for those (could be slow) or if we modify spree's user table to have `user_id` and `User` class to `has_many :addresses`.

LMK your thoughts

**Comment by bryanmtl** [comment]
Hey @joshnuss - I think we should modify the address table, adding the `user_id` field and then defining the `has_many :addresses` on 'Spree::User`

That should be quick and easy.

**Comment by joshnuss** [comment]
Was hoping wouldnt need any migrations :)

What do you think if I open a PR to spree_core? Seems everyone can use this feature

**Comment by bryanmtl** [comment]
@joshnuss Bumping this. We have added these relationships to H&C and return the collection of shipping addresses when a user logs in. Injecting these addresses into the checkout flow is the remaining piece here.

**Comment by DanielWright** [comment]
Are there other objects in the domain, not associated with a customer, that
can have an address? That's the only reason I can think of that Spree
wouldn't have already created a direct association between addresses and
users. Maybe the whole `Spree.user_class` abstraction?

As a workaround, you could define an `addresses` method on User's public
interface that pulls addresses from the user's previous orders. You'd lose
the arbitrariness of entries in an "address book," but that's not a super
valuable feature.

**Comment by joshnuss** [comment]
Each order object must point to a unique billing/shipping address record, because if the address is edited post-sale, you wouldnt want older order's data to change too.

What spree should be doing, is when the order is completed (checkout), a record of each bill/ship address is added to the addresses table (unless the same address already exists). 

That way you would have a list of addresses for each customer (address book) which can be used when creating new orders. And editing these addresses wont effect order data (and vice versa).

**Comment by joshnuss** [comment]
@DanielWright we could pull address data from the old orders, but the query would slow things down any time we need to render an order

**Comment by bryanmtl** [comment]
We are doing this now: https://github.com/sprangular/sprangular/blob/master/app/models/spree/user_decorator.rb#L16-L22

**Comment by joshnuss** [comment]
Think this should fix it

https://github.com/sprangular/sprangular/commit/93613f1
