### ISSUE TITLE
Checkout failing brings back to first step without error message

### ISSUE THREAD

**Issue by LaurentDario** [sprangular/sprangular#91]
I tried to access the complete.html.slim page by completing an order using the "4242424242424242" credit card, but when I click on "Place Order" I end up back to the first step of the checkout without any error message.

Is this caused by the credit card being rejected ? If so, is there a way to know that this is the reason to add an error message on the page ?

**Comment by joshnuss** [comment]
This is now fixed. The full error message is displayed in the checkout page.
Will be adding an error map, so that we can display more friendly messages.
