### ISSUE TITLE
Checkout needs a state to refresh rates

### ISSUE THREAD

**Issue by LaurentDario** [sprangular/sprangular#93]
As the address verification is based on the fact that all fields are filled, the shipping rates won't refresh with an address with no state.

**Comment by joshnuss** [comment]
@LaurentDario Think this is the correct behaviour, cause rates could be different by state (i.e. Alaska not the same rate as Hawaii)

**Comment by bryanmtl** [comment]
@joshnuss What about countries with no states?

**Comment by joshnuss** [comment]
@bryanmtl plan to support that too, expect this to be resolved in the next couple days
