### ISSUE TITLE
First Load Performance Problems. 

### ISSUE THREAD

**Issue by rposborne** [sprangular/sprangular#94]
We are seeing some regressions / optimizations for the first load of the application.  Since the i18n branch has been merged first loads are taking upwards of 5000ms.  We have wrapped a few things and just straight up cache things, which has worked well but not sure if these should be brought upstream or not.

**Comment by bryanmtl** [comment]
@rposborne Thanks for pointing this out. The main issue is Spree's current implementation for the products API is super slow. There are a few n+1 issues that I've been working to solve. I'd be curious to see how you've addressed the slowness with caching, but the real fix lies in improving the performance of the queries and bringing the template rendering times down.

Would you mind opening up a PR with your caching experiments?

**Comment by joshnuss** [comment]
@bryanmtl @rposborne i18n also decreased slowness, see http://sprangular-demo.herokuapp.com

cold boot (CTRL+F5) takes 15s
warm boot (F5) takes 2-3s

(its running on heroku so ignore the first-time access load time)

**Comment by joshnuss** [comment]
*increased slowness

**Comment by joshnuss** [comment]
@bryanmtl you are right, it doesnt seem to have anything to do with i18n, its the products lookup.

Order data is rendered inside the first request, and order data contains product data.
So initial page loading time can be highly variable, like if you have an empty cart relatively fast, 10 items in cart - super slow.

**Comment by joshnuss** [comment]
Same issue with slowness when adding to cart, the more items added, the slower things get

**Comment by rposborne** [comment]
So most of the performance issues we have see relates to the JS env, establishing what templates need to be delivered [approx 1s here ](https://github.com/sprangular/sprangular/blob/master/app/helpers/sprangular/application_helper.rb#L15-L23) and calling translations [approx 1-3 seconds here](https://github.com/sprangular/sprangular/blob/master/app/helpers/sprangular/application_helper.rb#L56-L64) wrapping these calls in Rails.cache.fetch, gets us down to about 200 ms on first page load, not including follow up calls from angular.  

These times assumes dev environment with caching turned on, and respective caches, primed / memoized.

**Comment by joshnuss** [comment]
Thanks @rposborne, that was a great suggestion.

@bryanmtl opening a new issue for stock lookup performance

**Comment by bryanmtl** [comment]
Great. I have a branch of spree that addresses this. 



-- 
 
BRYAN MAHONEY
bryan@godynamo.com
http://twitter.com/#!/bryanmtl
 DYNAMO
http://www.goDynamo.com
http://twitter.com/dynamomtl
http://facebook.com/dynamomtl
 
TEL 514 499 2843 x21 | CEL 514 804 2843
439 Rue St-Pierre, Vieux-Montréal, Québec H2Y2M8 CANADA
