### ISSUE TITLE
Asset pipeline rule causing undefined variable error in Sass

### ISSUE THREAD

**Issue by fuzzytern** [sprangular/sprangular#95]
As exposed in [this SO post](http://stackoverflow.com/questions/28832259/undefined-variable-alert-padding-using-rails-angularjs-and-bootstrap/28857130#28857130), I've been struggling precompiling assets on a bare setup of sprangular.

As further described in the aformentioned post, the assets precompiling hangs with the following message:

    ** Execute assets:precompile
    rake aborted!
    Sass::SyntaxError: Undefined variable: "$alert-padding".
       (in /home/owner/.rvm/gems/ruby-2.1.5/gems/bootstrap-sass-3.3.3/assets/stylesheets/bootstrap/_alerts.scss:10)

I just realized that if comment out [this precompile rule in `lib/sprangular/engine.rb`](https://github.com/sprangular/sprangular/blob/master/lib/sprangular/engine.rb#L13) (and source the `sprangular` gem locally) then I can execute `bundle exec rake assets:precompile` in my app flawlessly.

Was there a specific reason for that precompile rule? Do we really want to precompile all bootstrap files?
How should I edit the config in my app so I don't have to mess around with sprangular's code?

Just for the record, here are some of the gems I use in my app:

    rails (4.2.0)
    bootstrap-sass (3.3.3)
    sass-rails (5.0.1)
    sprangular (0.0.1)
    spree_api (3.0.0.rc5 2cf488e)
    spree_auth_devise (3.0.0 07f1625)
    spree_backend (3.0.0.rc5 2cf488e)
    spree_core (3.0.0.rc5 2cf488e)
    spree_gateway (3.0.0.beta bcd933e)
    spree_sample (3.0.0.rc5 2cf488e)

**Comment by joshnuss** [comment]
Hi @fuzzytern,

spree 3.0.0.rc & rails 4.2 is not yet supported. (coming soon, pr's welcome)

**Comment by joshnuss** [comment]
Should note. we are currently using rails-assets-bootstrap-sass-official in master (and in the process of migrating from Bootstrap to Bourbon)
